// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/who-am-i.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var who_am_i_default = defineTool({
  name: "who_am_i",
  title: "Who am I",
  description: "Return the signed-in Elsa Workflows user: user id, email, and display name from their profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const userId = ctx.getUserId();
    const { data, error } = await supabaseForUser(ctx).from("user_profiles").select("user_id, display_name, avatar_url").eq("user_id", userId).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      userId,
      email: ctx.getUserEmail(),
      displayName: data?.display_name ?? null,
      avatarUrl: data?.avatar_url ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-organizations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_organizations_default = defineTool2({
  name: "list_my_organizations",
  title: "List my organizations",
  description: "List the Elsa Workflows organizations the signed-in user belongs to, with role, slug, and id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("organization_members").select("role, organization:organizations(id, name, slug, contact_email, created_at)").eq("user_id", ctx.getUserId());
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const orgs = (data ?? []).map((row) => ({
      id: row.organization?.id,
      name: row.organization?.name,
      slug: row.organization?.slug,
      role: row.role,
      contactEmail: row.organization?.contact_email,
      createdAt: row.organization?.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(orgs, null, 2) }],
      structuredContent: { organizations: orgs }
    };
  }
});

// src/lib/mcp/tools/get-organization-credits.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_organization_credits_default = defineTool3({
  name: "get_organization_credits",
  title: "Get organization credit balance",
  description: "Summarize active credit lots for an organization the user belongs to. Provide the organization slug (e.g. 'acme'). Returns per-provider totals of purchased vs remaining minutes.",
  inputSchema: {
    organizationSlug: z.string().trim().min(1).describe("The organization's URL slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organizationSlug }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const supabase = supabaseForUser3(ctx);
    const { data: org, error: orgError } = await supabase.from("organizations").select("id, name, slug").eq("slug", organizationSlug).maybeSingle();
    if (orgError)
      return { content: [{ type: "text", text: orgError.message }], isError: true };
    if (!org)
      return {
        content: [{ type: "text", text: `Organization "${organizationSlug}" not found or not accessible.` }],
        isError: true
      };
    const { data: lots, error: lotsError } = await supabase.from("credit_lots").select("service_provider_id, minutes_purchased, minutes_remaining, status, expires_at").eq("organization_id", org.id);
    if (lotsError)
      return { content: [{ type: "text", text: lotsError.message }], isError: true };
    const byProvider = /* @__PURE__ */ new Map();
    for (const lot of lots ?? []) {
      if (lot.status !== "active") continue;
      const key = lot.service_provider_id;
      const prev = byProvider.get(key) ?? { minutesPurchased: 0, minutesRemaining: 0, lots: 0 };
      prev.minutesPurchased += lot.minutes_purchased ?? 0;
      prev.minutesRemaining += lot.minutes_remaining ?? 0;
      prev.lots += 1;
      byProvider.set(key, prev);
    }
    const providers = Array.from(byProvider.entries()).map(([serviceProviderId, v]) => ({
      serviceProviderId,
      ...v,
      hoursRemaining: Math.round(v.minutesRemaining / 60 * 100) / 100
    }));
    const payload = { organization: org, providers };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tehhrjepyfnhmsgtwzkf";
var mcp_default = defineMcp({
  name: "elsa-workflows-mcp",
  title: "Elsa Workflows",
  version: "0.1.0",
  instructions: "Tools for the Elsa Workflows platform. Use `who_am_i` to confirm the signed-in user, `list_my_organizations` to enumerate the user's organizations, and `get_organization_credits` to inspect Expert Services credit balances by organization slug.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [who_am_i_default, list_my_organizations_default, get_organization_credits_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
