// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tehhrjepyfnhmsgtwzkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaGhyamVweWZuaG1zZ3R3emtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNjQ5NzUsImV4cCI6MjA4NDk0MDk3NX0.LiAZ64iHHTraulE7dcb9ZwKgtvhVVhAyv3znFkly4JQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});