/**
 * Central version anchor for all Get Started guides.
 *
 * Every Elsa and Elsa Studio package referenced in the guides must be
 * pinned to this exact version so the walkthroughs stay coherent from a
 * clean checkout. When a new Elsa release is published:
 *
 *   1. Bump ELSA_VERSION below.
 *   2. Re-run each guide from an empty directory:
 *        dotnet restore && dotnet build && dotnet run
 *   3. Update SUPPORTED_DOTNET_SDKS if the release changes SDK support.
 *   4. Update LAST_VERIFIED_ON.
 *
 * Elsa and Elsa Studio ship on the same release line, so a single
 * version applies to both.
 */
export const ELSA_VERSION = "3.8.0";

/** Publication date of the pinned Elsa release. */
export const ELSA_RELEASE_DATE = "2026-09-05";

/** Official release notes for the pinned release line. */
export const ELSA_RELEASE_LINKS = {
  core: `https://github.com/elsa-workflows/elsa-core/releases/tag/${ELSA_VERSION}`,
  studio: `https://github.com/elsa-workflows/elsa-studio/releases/tag/${ELSA_VERSION}`,
  extensions: `https://github.com/elsa-workflows/elsa-extensions/releases/tag/${ELSA_VERSION}`,
} as const;

/**
 * The `Elsa.Templates` package ships on its own cadence and is NOT part of the
 * Elsa Core / Studio release line. The 3.8.0 template package is tagged and
 * released (Elsa Core / Studio 3.8.0 references, CShells 0.0.28, .NET 10
 * generated projects) at commit c44079008d06f4580374d7c8abbeff2faf748df0.
 * Release: https://github.com/elsa-workflows/elsa-templates/releases/tag/3.8.0
 */
export const ELSA_TEMPLATES_VERSION = "3.8.0";

/** Template release tag. */
export const ELSA_TEMPLATES_RELEASE_URL =
  "https://github.com/elsa-workflows/elsa-templates/releases/tag/3.8.0";


/** Target framework of projects generated by the 3.8.0 templates. */
export const ELSA_TEMPLATES_TARGET_FRAMEWORK = "net10.0";

/** CShells version referenced by the 3.8.0 templates (shell feature model). */
export const ELSA_TEMPLATES_CSHELLS_VERSION = "0.0.28";

/** Live upgrade guide for the 3.8.0 release line. */
export const ELSA_UPGRADE_GUIDE_URL =
  "https://docs.elsaworkflows.io/getting-started/upgrading-to-3.8";


/** .NET SDKs the pinned Elsa release is tested against. */
export const SUPPORTED_DOTNET_SDKS = ["8.0", "9.0", "10.0"] as const;

/**
 * ISO date of the last clean-room verification of the guides
 * (performed against Elsa 3.7.1).
 */
export const LAST_VERIFIED_ON = "2026-07-18";

/**
 * ISO date on which the package versions and registration APIs on these pages
 * were checked against the tagged 3.8.0 sources and NuGet.org.
 */
export const PACKAGES_CHECKED_ON = "2026-09-05";

/** Convenience helper for `dotnet add package` snippets. */
export const pkg = (name: string) =>
  `dotnet add package ${name} --version ${ELSA_VERSION}`;
